import type { Metadata } from "next";
import "./globals.css";
import { RootProvider } from "~/components/provider";
import { NotificationAlert } from "~/components/ui/alert/notification.alert";
import { ErrorAlert } from "~/components/ui/alert/error.alert";
import { inter } from "~/lib/font";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`antialiased overflow-x-hidden ${inter.className} bg-gray-100 text-gray-800 tracking-wide`}
            >
                <RootProvider>
                    <NotificationAlert />
                    <ErrorAlert />
                    {children}
                </RootProvider>
            </body>
        </html>
    );
}
